### ISSUE TITLE
Issue with release `Release with tag_name 0.xxx.0 not found`

### ISSUE THREAD

**Issue by patrick91** [autopub/autopub#26]
I've recently been getting the following error (it happened in the last 2 releases):

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/bin/autopub", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/autopub/autopub.py", line 83, in main
    arguments.func(arguments)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/autopub/autopub.py", line 33, in githubrelease
    create_github_release()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/autopub/create_github_release.py", line 50, in create_github_release
    asset_pattern="dist/*",
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github_release.py", line 116, in with_check_for_credentials
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github_release.py", line 469, in gh_release_create
    gh_asset_upload(repo_name, tag_name, asset_pattern, dry_run=dry_run)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github_release.py", line 116, in with_check_for_credentials
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github_release.py", line 724, in gh_asset_upload
    upload_url = get_release_info(repo_name, tag_name)["upload_url"]
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github_release.py", line 272, in get_release_info
    raise Exception('Release with tag_name {0} not found'.format(tag_name))
Exception: Release with tag_name 0.100.0 not found
```

See an example here: https://github.com/strawberry-graphql/strawberry/runs/5434280998?check_suite_focus=true

Not sure if something changed in GitHub's API 🤔

**Comment by patrick91** [comment]
~Ok, it looks githubreleases doesn't find the release because it doesn't paginate the releases: https://github.com/j0057/github-release/blob/master/github_release.py#L311-L320~

I was wrong, maybe the library needs a bit of timeout afer creating the release, here: https://github.com/j0057/github-release/blob/master/github_release.py#L533-L534

**Comment by patrick91** [comment]
https://github.com/patrick91/autopub/blob/fix/release-not-found/autopub%2Fcreate_github_release.py#L45-L66

this seems to fix things 😊

**Comment by minchinweb** [comment]
@patrick91 does adding the delay seem to fix it on your side? If so, any chance you could create a pull request?

**Comment by patrick91** [comment]
I'd need to check what @justinmayer thinks of it 😊

**Comment by justinmayer** [comment]
Hey Patrick! Many thanks for reporting this and for looking into how to fix it. If that delay you added seems to address the problem, then I think it's a perfectly good solution. Would you mind submitting a pull request so we can issue a release containing your fix?

**Comment by patrick91** [comment]
sorry for the late reply, I've scheduled some time for this issue this week :)

**Comment by justinmayer** [comment]
Hey Patrick! Any chance you might have a moment to submit a PR for this issue? It'd be nice to address this problem for folks who are using AutoPub. I'm sure you are swamped, so no worries if you can't manage it right now. 😅
