### ISSUE TITLE
404 Client Error: Not Found for url 

### ISSUE THREAD

**Issue by nrbnlulu** [autopub/autopub#36]
Maybe I have some wrong tokens though, do you know what's the issue?
https://github.com/nrbnlulu/qtgql/actions/runs/4052819281/jobs/6972689626
```console
Creating virtualenv qtgql-vCo0FpIN-py3.11 in /home/runner/.cache/pypoetry/virtualenvs
Building qtgql (0.103.0)
To https://github.com/nrbnlulu/qtgql
   1b126c3..18e9b1a  HEAD -> main
To https://github.com/nrbnlulu/qtgql
 * [new tag]         0.103.0 -> 0.103.0
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/bin/autopub", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/autopub/autopub.py", line 83, in main
    arguments.func(arguments)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/autopub/autopub.py", line 33, in githubrelease
    create_github_release()
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/autopub/create_github_release.py", line 45, in create_github_release
    gh_release_create(
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/github_release.py", line 132, in with_check_for_credentials
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/github_release.py", line 545, in gh_release_create
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/requests/models.py", line 10[21](https://github.com/nrbnlulu/qtgql/actions/runs/4052819281/jobs/6972689626#step:5:22), in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/nrbnlulu/qtgql/releases
```

Note that I tried to re-run this workflow and it caused another error.
https://github.com/nrbnlulu/qtgql/actions/runs/4052819281/jobs/6972716375

**Comment by justinmayer** [comment]
The origin of that error appears to be related to the [GitHub Release](https://github.com/j0057/github-release) package. One possible explanation is that said package is not quite ready for Python 3.11. I suggest pinning the [`python-version`](https://github.com/nrbnlulu/qtgql/blob/main/.github/workflows/release.yml#L19) to `"3.9"` instead of the less-specific `"3.x"` value that you currently have. Could you try that and let me know if that resolves the problem?

Regarding re-running the workflow, please know that AutoPub workflow runs are not currently designed to be idempotent, so it's natural that re-running the workflow would not yield predictable results. For example, in this case, [AutoPub already processed the `RELEASE.md` file](https://github.com/nrbnlulu/qtgql/commit/18e9b1a89320228724e175bdd0fd41e598e8916a), replacing it and committing changes to `CHANGELOG.md`, incrementing the version number, etc., so you can't just re-run that workflow again and expect that AutoPub will understand the half-finished state that the previous run left behind. In this case, you should probably finish the remaining steps by hand (manually create a GitHub release, manually publish the current package to PyPI), then (hopefully) fix the problem via my suggestion above, and then let AutoPub take care of the _next_ release. Does that make sense?

**Comment by nrbnlulu** [comment]
Yeah, thanks! I'll let you kow if downgrading resoves that

**Comment by nrbnlulu** [comment]
I think it was a token problme after all, I didn't realized I should create a new **real** github user instead of an github app. anyways it works now, Thanks!
